apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/arvindan1308/argocd-multitenant-test
        revision: main
        files:
          - path: "customers/*/values.yaml"
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: '{{.argoProject}}'
      source:
        repoURL: https://github.com/arvindan1308/argocd-multitenant-test
        targetRevision: main
        path: helm-chart
        helm:
          valueFiles:
            - values-common.yaml
            - '../customers/{{.path.basename}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
