apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __CUSTOMER__
  namespace: argocd
spec:
  project: __PROJECT__
  source:
    repoURL: https://github.com/arvindan1308/argocd-multitenant-test
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values-common.yaml
        - ../customers/__CUSTOMER__/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: __CUSTOMER__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
