apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wayne
  namespace: argocd
spec:
  project: workflow
  source:
    repoURL: https://github.com/arvindan1308/argocd-multitenant-test
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values-common.yaml
        - ../customers/wayne/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wayne
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
